dist: trusty
sudo: required
language: python

services:
- docker

python:
- 2.6
- 2.7
- 3.4
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev
- nightly
- pypy-5.3.1

env:
- SINGVER=2.4.6

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq python dh-autoreconf squashfs-tools build-essential
- wget https://github.com/singularityware/singularity/releases/download/$SINGVER/singularity-$SINGVER.tar.gz
- tar xvf singularity-$SINGVER.tar.gz
- cd singularity-$SINGVER
- ./configure --prefix=/usr/local --sysconfdir=/etc
- make
- sudo make install
- singularity --version
- cat /etc/singularity/singularity.conf
- cd ${TRAVIS_BUILD_DIR}

install:
- pip install --upgrade setuptools
- pip install coveralls pytest pytest-runner pycodestyle
- pip install .

script:
- pycodestyle --max-line-length=80 *.py tests/*.py
- coverage run --source conp-pipeline setup.py pytest

after_success:
- coveralls

deploy:
